version: '3.5'

services:

  im-user-mongodb:
    image: mongo:4.2.2
    container_name: im-user-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - im-usersvc-mongodb:/data/db
    networks:
      - im-network

  im-user-backend:
    build: ../im-user-backend
    image: im-user-backend
    container_name: im-user-backend
    environment:
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@im-user-mongodb:27017
      - EXPRESS_PORT=8080
    ports:
      - "0.0.0.0:8081:8080"
    command: npm start
    networks:
      - im-network
    depends_on:
      - im-user-mongodb

  im-identity-backend:
    build: ../im-identity-backend
    image: im-identity-backend
    container_name: im-identity-backend
    environment:
      - USER_SERVICE_ENDPOINT=http://im-user-backend:8080/api/usersvc/users
      - EXPRESS_PORT=8080
    ports:
      - "0.0.0.0:8082:8080"
    command: npm start
    networks:
      - im-network
    depends_on:
      - im-user-backend

volumes:
  im-usersvc-mongodb:

networks:
  im-network:
    name: im-network
    driver: bridge
