version: '3.5'

services:

  um-usersvc-mongodb:
    image: mongo:4.2.2
    container_name: um-usersvc-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - um-usersvc-mongodb:/data/db
    networks:
      - um-network

  um-usersvc-api:
    build: ../um-userservice
    image: um-usersvc-api
    container_name: um-usersvc-api
    environment:
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@um-usersvc-mongodb:27017
      - EXPRESS_PORT=8080
    ports:
      - "0.0.0.0:8080:8080"
    command: npm start
    networks:
      - um-network
    depends_on:
      - um-usersvc-mongodb

  um-authsvc-api:
    build: ../um-authservice
    image: um-authsvc-api
    container_name: um-authsvc-api
    environment:
      - USER_SERVICE_ENDPOINT=http://um-usersvc-api:8080/api/users
      - EXPRESS_PORT=8080
    ports:
      - "0.0.0.0:8081:8080"
    command: npm start
    networks:
      - um-network
    depends_on:
      - um-usersvc-api

volumes:
  um-usersvc-mongodb:

networks:
  um-network:
    name: um-network
    driver: bridge
