version: '3.5'

services:

  user-mongodb:
    image: mongo:4.2.2
    container_name: user-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - user-mongodb:/data/db
    networks:
      - usermanager-network

volumes:
  user-mongodb:

networks:
  usermanager-network:
    name: usermanager-network
    driver: bridge
